---
ruby_checksum:        "08e3d4b85b8a1118a8e81261f59dd8b4ddcfd70b6ae554e0ec5ceb99c3185e8a"
ruby_library_version: "2.0.0"
ruby_version:         "2.0.0-p247"

ruby_location:        "/opt/ruby-{{ ruby_version }}"
