---
- name: Add the deploy user
  user: name=deploy
        home=/home/deploy
        shell=/bin/bash
        comment="Deploy User"

- name: Set up authorized_keys for the deploy user
  authorized_key: user=deploy
                  state=present
                  key="{{ item }}"
  with_file:
    - public_keys/lund-joshua
